version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - yum install git -y
      - yum install zip -y     
      - git clone https://github.com/Dgruploads/AWS.git
      - cp -R AWS/CodeDeploy/* target/
      - zip -r target/sample-web-app.war target/scripts target/appspec.yml sample-web-app.zip
      - aws s3 cp sample-web-app.zip s3://dgruploads-build-artifacts
artifacts:
  files:
    - target/sample-web-app.war
